version: '3'
services:
 mysql:
   image: mysql:8.0.13
   command: --default-authentication-plugin=mysql_native_password
   volumes:
     - "./mysql-data:/var/lib/mysql"
   environment:
     MYSQL_ROOT_PASSWORD: root

 app:
   build: .
   volumes:
     - ".:/app"
   ports:
     - "3000:3000"
   security_opt:
     - seccomp:unconfined
   tty: true
   depends_on:
     - mysql
